# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "someipd_test",
    srcs = ["someipd_test.py"],
    args = [
        "$(location //score/someipd:someipd)",
        "$(location //score/config:config_file)",
    ],
    data = [
        "//score/config:config_file",
        "//score/someipd",
    ],
    tags = [
        "unit",
    ],
    target_compatible_with = ["@platforms//os:linux"],
    deps = [
        "//quality/pytest:process",
    ],
)

cc_test(
    name = "local_network_service_test",
    size = "small",
    srcs = ["local_network_service_test.cpp"],
    tags = ["unit"],
    deps = [
        "//score/config:config_flatbuffers",
        "//score/socom",
        "//score/socom:mock",
        "//score/someipd:local_network_service",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
